### ISSUE TITLE
Python 3.9 Support - base64.encodestring/encodebytes

### ISSUE THREAD

**Issue by GlenRSmith** [flexxui/pscript#58]
Similar to #50:

```
✗ pip freeze
dialite==0.5.3
flexx==0.8.1
pscript==0.7.5
tornado==6.1
webruntime==0.5.8
```

```
Python 3.9.4 (default, Apr  5 2021, 01:49:30)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from flexx import flx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gsmith/Envs/phibes_gui/lib/python3.9/site-packages/flexx/flx.py", line 10, in <module>
    from .app import *
  File "/Users/gsmith/Envs/phibes_gui/lib/python3.9/site-packages/flexx/app/__init__.py", line 38, in <module>
    from ._app import App, manager
  File "/Users/gsmith/Envs/phibes_gui/lib/python3.9/site-packages/flexx/app/_app.py", line 11, in <module>
    from base64 import encodestring as encodebytes
ImportError: cannot import name 'encodestring' from 'base64' (/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py)
```

**Comment by almarklein** [comment]
Yes, py39 supprt has been added to pscript, but not yet to flexx.

**Comment by almarklein** [comment]
The corresponding issue is https://github.com/flexxui/flexx/issues/674
